# Setup
title:            Hoa T. Bui
description:      This is my personal page
url:              cochinh-thanphu.github.io
baseurl:          /

author:
  name:           'Hoa Bui'
  url:            https://scholar.google.com/citations?user=aY5Esg4AAAAJ&hl=en

paginate:         5

relative_links:
  enabled: true
  collections: true
  include:
    - CONTRIBUTING.md
    - README.md
    - LICENSE.md
    - COPYING.md
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - ISSUE_TEMPLATE.md
    - PULL_REQUEST_TEMPLATE.md
